---
template_path: cloudwatch/alarm.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  alarms: !file generated-config/ec2instance.yaml


stack_tags:
  Group: cloudwatch-alarm
  Owner: Haris Fauzi
